worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
	
    map $http_x_target_page $target_file {
        "secret"  /src/state/secret.html;
        "beta"    /src/state/beta.html;
        default   /src/state/error.html;
    }

    server {
        listen       80;
        server_name  localhost;
        return 301 https://$host$request_uri;
    }

    # HTTPS Server
    server {
        listen       443 ssl;
        server_name  localhost;

        ssl_certificate      D:/nginx/conf/server.crt;
        ssl_certificate_key  D:/nginx/conf/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers  HIGH:!aNULL:!MD5;

        root  "D:/learn/web_nginx";
        index index.html;

        location = /get-hacker-page {
            default_type text/html;
            try_files $target_file =404;
        }
        
        location = /trigger {
            alias "D:/learn/web_nginx/src/state/trigger.html";
            default_type text/html;
            add_header Cache-Control "no-store";
        }		

        location = /api/get-state {
            default_type text/html;
            try_files $target_file =404;
        }

        location = /stack {	
            alias "D:/learn/web_nginx/src/stack/index.html";
            default_type text/html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        }

        location = /hacker {
            alias "D:/learn/web_nginx/src/hacker/index.html";
            default_type text/html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        }

        location ~ ^/hacker/([^/.]+)$ {
            default_type text/html;
            alias "D:/learn/web_nginx/src/hacker/profile.html";
        }
        location /node-api/ {
            proxy_pass https://127.0.0.1:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        location /django-api/ {
            proxy_pass http://127.0.0.1:8000/;
            proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ =404;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}